// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlockItem: typeof import('./../src/components/BlockItem.vue')['default']
    EmailBlock: typeof import('./../src/components/EmailBlock.vue')['default']
    EmailComponent: typeof import('./../src/components/EmailComponent.vue')['default']
    EmailContent: typeof import('./../src/components/EmailContent.vue')['default']
    EmailDesign: typeof import('./../src/components/EmailDesign.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    IconsIconCommunity: typeof import('./../src/components/icons/IconCommunity.vue')['default']
    IconsIconDocumentation: typeof import('./../src/components/icons/IconDocumentation.vue')['default']
    IconsIconEcosystem: typeof import('./../src/components/icons/IconEcosystem.vue')['default']
    IconsIconSupport: typeof import('./../src/components/icons/IconSupport.vue')['default']
    IconsIconTooling: typeof import('./../src/components/icons/IconTooling.vue')['default']
    LayoutItem: typeof import('./../src/components/LayoutItem.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NH2: typeof import('naive-ui')['NH2']
    NH3: typeof import('naive-ui')['NH3']
    NH4: typeof import('naive-ui')['NH4']
    NH5: typeof import('naive-ui')['NH5']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./../src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./../src/components/WelcomeItem.vue')['default']
  }
}
