// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlockItem: typeof import('@/components/widgetPanel/BlockItem.vue')['default']
    ContainerColumnContainer: typeof import('@/components/widgets/ColumnContainer.vue')['default']
    ContainerSectionContainer: typeof import('@/components/widgets/SectionContainer.vue')['default']
    DesignPanelDesignPanel: typeof import('./../src/components/designPanel/DesignPanel.vue')['default']
    DesignPanelEmailDesign: typeof import('./../src/components/designPanel/EmailDesign.vue')['default']
    EmailPanelEmailContent: typeof import('./../src/components/emailPanel/EmailContent.vue')['default']
    EmailPanelEmailPanel: typeof import('./../src/components/emailPanel/EmailPanel.vue')['default']
    IconsIconCommunity: typeof import('./../src/components/icons/IconCommunity.vue')['default']
    IconsIconDocumentation: typeof import('./../src/components/icons/IconDocumentation.vue')['default']
    IconsIconEcosystem: typeof import('./../src/components/icons/IconEcosystem.vue')['default']
    IconsIconSupport: typeof import('./../src/components/icons/IconSupport.vue')['default']
    IconsIconTooling: typeof import('./../src/components/icons/IconTooling.vue')['default']
    LayoutItem: typeof import('@/components/widgetPanel/LayoutItem.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NH3: typeof import('naive-ui')['NH3']
    NH4: typeof import('naive-ui')['NH4']
    NH5: typeof import('naive-ui')['NH5']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestContent: typeof import('./../src/components/testContent.vue')['default']
    WidgetPanelBlockItem: typeof import('./../src/components/widgetPanel/BlockItem.vue')['default']
    WidgetPanelEmailWidget: typeof import('./../src/components/widgetPanel/EmailWidget.vue')['default']
    WidgetPanelLayoutItem: typeof import('./../src/components/widgetPanel/LayoutItem.vue')['default']
    WidgetPanelWidgetPanel: typeof import('./../src/components/widgetPanel/WidgetPanel.vue')['default']
    WidgetsColumnContainer: typeof import('./../src/components/widgets/ColumnContainer.vue')['default']
    WidgetsSectionContainer: typeof import('./../src/components/widgets/SectionContainer.vue')['default']
    WrapperBorderWrapper: typeof import('./../src/components/wrapper/BorderWrapper.vue')['default']
  }
}
