// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DesignPanelDesignPanel: typeof import('./../components/designPanel/DesignPanel.vue')['default']
    EmailPanelEmailPanel: typeof import('./../components/emailPanel/EmailPanel.vue')['default']
    IconsIconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconsIconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconsIconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconsIconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconsIconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NH3: typeof import('naive-ui')['NH3']
    NH4: typeof import('naive-ui')['NH4']
    NH5: typeof import('naive-ui')['NH5']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WidgetPanelBlockItem: typeof import('./../components/widgetPanel/BlockItem.vue')['default']
    WidgetPanelLayoutItem: typeof import('./../components/widgetPanel/LayoutItem.vue')['default']
    WidgetPanelWidgetPanel: typeof import('./../components/widgetPanel/WidgetPanel.vue')['default']
    WidgetsColumnContainer: typeof import('./../components/widgets/ColumnContainer.vue')['default']
    WidgetsSectionContainer: typeof import('./../components/widgets/SectionContainer.vue')['default']
    WrapperContainerWrapper: typeof import('./../components/wrapper/ContainerWrapper.vue')['default']
  }
}
